# Generated by Django 4.1 on 2023-06-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_editor", "0003_alter_programcode_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcode",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
    ]
