// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  WHITESPACE = 1,
  Program = 2,
  Statement = 3,
  Keyword = 4,
  Identifier = 5,
  Punctuation = 6,
  Number = 7
