// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Function = 2,
  Func = 3,
  FuncName = 4,
  Name = 5,
  Args = 6,
  Arg = 7,
  Type = 8,
  Block = 9,
  FunctionCall = 10,
  Params = 11,
  IfExpression = 12,
  If = 13,
  Number = 14,
  Float = 15,
  BinaryExpression = 16
