// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {quantaHighlight} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: ")xQQOPOOOcOPO'#C`O#]OPO'#C^O#bOPO'#CfO#gOPO'#ChO$vOPO'#CvOOOO'#Cz'#CzQQOPOOOOOO'#C`'#C`O%aOPO,58xO%fOPO,59QOQOPO,59SOOOO'#Cm'#CmOOOO'#Cn'#CnOOOO'#Co'#CoOOOO'#Cp'#CpOOOO'#Cq'#CqOOOO'#Cr'#CrOOOO'#Cs'#CsOOOO'#Ct'#CtOOOO'#Cu'#CuOQOPO,59WOQOPO,59WOQOPO,59WOQOPO,59WOQOPO,59WOQOPO,59WOQOPO,59WOQOPO,59WOQOPO,59WOOOO-E6t-E6tO%mOPO1G.dO%uOPO'#CgOOOO1G.l1G.lO&POPO1G.lO&UOPO1G.nO'|OPO1G.rOOOO1G.r1G.rO(WOPO1G.rO*UOPO1G.rO*]OPO1G.rO,WOPO1G.rO,_OPO1G.rO.YOPO1G.rO.aOPO1G.rO.hOPO'#CcO.mOPO'#CbO.uOPO7+$OO.zOPO7+$OOQOPO'#CxO/POPO,59ROOOO7+$W7+$WO.uOPO7+$YOOOO,58},58}O/XOPO'#CwO/^OPO,58|O/fOPO'#CeOOOO<<Gj<<GjO.uOPO<<GjO/mOPO,59dOOOO-E6v-E6vOOOO<<Gt<<GtOOOO,59c,59cOOOO-E6u-E6uOOOO,59P,59PO/wOPO,59POOOOAN=UAN=UOOOO1G.k1G.k",
  stateData: "0W~ORQOTPO]SO^UO_UO~ORnXTnX]nX^nX_nXmnXoSXtnXunXvnXwnXxnXynXznX{nX|nX}nX!OnX!PnX!QnX!RnX!SnX!TnX!UnX!VnXpnXqnXsnX~OTWO~OoYO~OoZO~Ot[Ou[Ov]Ow]Ox]Oy^Oz^O{_O|`O}aO!ObO!PbO!QbO!RbO!SbO!TbO!UcO!VdO~ORjXTjX]jX^jX_jXmjXsjX~P#lOooO~OqqO~PQOW}Oq!PO~Op!ROqZX~P#lOq!TO~Oq!UO~P#lOv]Ow]Ox]OR`iT`i]`i^`i_`im`iy`iz`i{`i|`i}`i!O`i!P`i!Q`i!R`i!S`i!T`i!U`i!V`ip`iq`is`i~Ot`iu`i~P&]Ot[Ou[O~P&]Ot[Ou[Ov]Ow]Ox]Oy^Oz^OR`iT`i]`i^`i_`im`i|`i}`i!O`i!P`i!Q`i!R`i!S`i!T`i!U`i!V`ip`iq`is`i~O{`i~P(bO{_O~P(bOt[Ou[Ov]Ow]Ox]Oy^Oz^O{_O|`OR`iT`i]`i^`i_`im`i!O`i!P`i!Q`i!R`i!S`i!T`i!U`i!V`ip`iq`is`i~O}`i~P*dO}aO~P*dOt[Ou[Ov]Ow]Ox]Oy^Oz^O{_O|`O}aO!ObO!PbO!QbO!RbO!SbO!TbOR`iT`i]`i^`i_`im`i!V`ip`iq`is`i~O!U`i~P,fO!UcO~P,fOT!VO~Op!WOqUX~Or!YO~Oq![O~Op!ROqZa~OW}O~Op!WOqUa~Os!bO~PQOplaqla~P#lOs!eO~PQOWR]T_^T~",
  goto: "&`oPPpP!SP!i!lP!rp!{pPPPp#O#]#k#w$S$^$g$o$v$|%W%^P%dqUOVYZefghijklm!R!Y!cpROVYZefghijklm!R!Y!cRXQR!QoQ!OoR!`!WQ!Z!PQ!_!UR!d![RrYgeTpsvwxyz{|!]ifTpstvwxyz{|!]egTpswxyz{|!]chTpsxyz{|!]aiTpsyz{|!]_jTpsz{|!]]kTps{|!]ZlTps|!]XmTps!]QVOSnV!cR!c!YQ!X!OR!a!XQ!SpR!^!SWTOV!Y!cQpYQsZQteQufQvgQwhQxiQyjQzkQ{lQ|mR!]!R",
  nodeNames: "⚠ Program Function Func FuncName Name Args Arg Type Block FunctionCall Params IfExpression If Number Float BinaryExpression ArithOp ArithOp BitOp BitOp BitOp BitOp CompareOp LogicOp LogicOp",
  maxTerm: 53,
  propSources: [quantaHighlight],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: ",}~Rkqr!vuv#Rvw#Wxy#eyz#jz{#o{|#t|}#y}!O$O!P!Q$T!Q![$Y!^!_$s!_!`%Y!`!a%e!c!}%z#Q#R&V#T#U%z#U#V&[#V#W'n#W#Y%z#Y#Z)U#Z#]%z#]#^+p#^#o%z#o#p,f#p#q,k#q#r,x~!yP!_!`!|~#RO!T~~#WOx~~#]P{~vw#`~#eO!U~~#jOo~~#oOq~~#tOv~~#yOt~~$OOp~~$TOu~~$YOw~~$_Q^~!O!P$e!Q![$Y~$hP!Q![$k~$pP_~!Q![$k~$xQ!Q~!^!_%O!_!`%T~%TOy~~%YO!R~~%]P!_!`%`~%eO!S~~%jQ!O~!_!`%p!`!a%u~%uO!P~~%zOz~~&PQT~!c!}%z#T#o%z~&[O|~~&aST~!c!}%z#T#c%z#c#d&m#d#o%z~&rST~!c!}%z#T#c%z#c#d'O#d#o%z~'TST~!c!}%z#T#`%z#`#a'a#a#o%z~'hQW~T~!c!}%z#T#o%z~'sST~!c!}%z#T#c%z#c#d(P#d#o%z~(UST~!c!}%z#T#`%z#`#a(b#a#o%z~(gST~!c!}%z#T#c%z#c#d(s#d#o%z~(xST~!c!}%z#T#f%z#f#g'a#g#o%z~)ZUT~!c!}%z#T#`%z#`#a)m#a#i%z#i#j*o#j#o%z~)rST~!c!}%z#T#c%z#c#d*O#d#o%z~*TRT~!c!}%z#T#U*^#U#o%z~*cST~!c!}%z#T#h%z#h#i'a#i#o%z~*tST~!c!}%z#T#b%z#b#c+Q#c#o%z~+VST~!c!}%z#T#V%z#V#W+c#W#o%z~+jQR~T~!c!}%z#T#o%z~+uUT~!c!}%z#T#Y%z#Y#Z,X#Z#b%z#b#c*^#c#o%z~,`Q]~T~!c!}%z#T#o%z~,kOr~~,pP}~#p#q,s~,xO!V~~,}Os~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 690
})
