 document      =  { SOI ~ source_file ~ EOI }
source_file   =  _{ forest | block }
block         =  { statement* }

forest 		  = { function+ }
bracket_block =  { "{" ~ block ~ "}" }
newline       = _{ "\n" | "\r" }
WHITESPACE    = _{ " " | "\t" | "\n" | "\r" }

fn_arg  = {ident ~ ":" ~ type_name}
fn_arg_list = {(fn_arg ~ ("," ~ fn_arg)*)?}
fn_header = { "func" ~ ident ~ "(" ~ fn_arg_list ~ ")" ~ ("->" ~ type_name)? }
function      =  { fn_header ~ "{" ~ block ~ "}" }

statement      =  { (command | init_statement | if_statement | for_statement | while_statement | return_statement) }
command        =  { function_call ~ ";" }
function_call  =  { ident ~ "(" ~ params? ~ ")" }
params         = _{ expression ~ ("," ~ expression)* }
init_statement =  { type_name? ~ initialization  ~ ";" }
initialization =  { noun ~ "=" ~ expression }

if_statement    =  { "if" ~ "(" ~ expression ~ ")" ~ bracket_block ~ else_block?}
else_block      = _{ "else" ~ bracket_block }
for_statement   =  { "for" ~ ident ~ "in" ~ range ~ bracket_block }
range           =  { "(" ~ numVar ~ ".." ~ numVar ~ ")" }
numVar          = _{ integer | noun }
while_statement =  { "while" ~ "(" ~ expression ~ ")" ~ bracket_block }
return_statement = { "return" ~ expression ~ ";" }

type_name      =  { array_type | primitive_type }
primitive_type = _{ "bool" | "int" | "color" | "float" }
array_type   = { "array<" ~ type_name ~ "," ~ integer ~ ">" }

number     = { decimal | integer }
expression = {
    monadicExpr
  | dyadicExpr
  | term
}

monadicExpr  = { operator ~ expression }
dyadicExpr   = { (monadicExpr | term) ~ operator ~ expression }
parenth_expr = { "(" ~ expression ~ ")" }

box = {"[" ~ expression ~ "]" }
noun = {ident ~ box* }
term = _{ decimal | integer | color | boolean | function_call | noun | array_literal | parenth_expr }

operator = {
  
  | "+"
  | "*"
  | "-"
  | "/"
  | "%"
  | "<"
  | ">"
  | "=="
  | "!="
  | ">="
  | "<="
  | "&&"
  | "||"
}
array_literal = { "{" ~ (term ~ ("," ~ term)*)?  ~ "}" }
boolean = { "true" | "false" }
color = @{"Color::" ~ ident}
integer = @{ "-"? ~ ASCII_DIGIT+ }
decimal = @{ "-"? ~ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT* }
ident   = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
string  = @{ "'" ~ ("''" | (!"'" ~ ANY))* ~ "'" }
COMMENT = _{ "NB." ~ (!"\n" ~ ANY)* }